blank_issues_enabled: false
contact_links:
  - name: Abhi Arya
    url: abhi@opennote.me
    about: Email me for any questions or concerns.
  - name: Opennote Labs Support
    url: support@opennote.me
    about: Please report any issues to the lab support team if required.
